<a href="https://colab.research.google.com/github/Kunalkumar9354/Leetcode-Practice/blob/main/funct_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
np.arange(1,4,2) #start end step (loop)

array([1, 3])

you cant reshape if there are more elements in array as compare to the shape you want

In [10]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [13]:
a=a.reshape(3,3)
print(a)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [17]:
b =np.arange(1,5)
print(b)

[1 2 3 4]


In [18]:
b=b.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [20]:
nums=np.arange(1,51)
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [26]:
nums=nums.reshape((10,5))
print(nums)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [27]:
nums = nums.flatten() #return the one dimension array
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [28]:
nums=nums.ravel()
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
