<a href="https://colab.research.google.com/github/Kunalkumar9354/Leetcode-Practice/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
l=[1,2,3,4,5]
print(l)

[1, 2, 3, 4, 5]


In [10]:
a=np.array([1,2,3,4,5,6])
print(a)  # 1d array

[1 2 3 4 5 6]


In [11]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)  # 2d array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [20]:
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c) #3-d array

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [7]:
type(a) #output #numpy.ndarray -- n dimension array

numpy.ndarray

In [13]:
print(a.size)#no of elements in an array
print(b.size)
print(c.size)

6
10
15


In [21]:
print(a.shape) # no of rows and column
print(b.shape)
print(c.shape)

(6,)
(2, 5)
(1, 3, 5)


In [24]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int64
int64
int64


In [28]:
c=np.array([[1,2,3,4,5],[6,7,8,9.9,10],[11,12,13,14,15]])
print(c) #3-d array

[[ 1.   2.   3.   4.   5. ]
 [ 6.   7.   8.   9.9 10. ]
 [11.  12.  13.  14.  15. ]]


In [26]:
print(c.dtype)

float64


In [29]:
c.transpose() # transpose rows into columns

array([[ 1. ,  6. , 11. ],
       [ 2. ,  7. , 12. ],
       [ 3. ,  8. , 13. ],
       [ 4. ,  9.9, 14. ],
       [ 5. , 10. , 15. ]])