<a href="https://colab.research.google.com/github/Kunalkumar9354/Leetcode-Practice/blob/main/numpy_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
np.empty((4,4),dtype = int) # randomly create an array with random data


array([[102193442135201,               0,    489626271856,
           481036337263],
       [   450971566194,    498216206433,    137438953573,
           476741369961],
       [   498216206435,    137438953580,    476741369958,
           137438953586],
       [   433791696996,    450971566198,    433791696995,
        135652247076864]])

In [6]:
np.ones((1)) #1 row and 1 column

array([1.])

In [8]:
np.ones((1,2)) #1 row 2 column

array([[1., 1.]])

In [11]:
np.ones((3,4),dtype=int) #3 rows 4columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.ones((3,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros((3,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
# np.ones((3,4),dtype=str)#  you will get an array containig ones str type
np.zeros((3,4),dtype=str) # you will get an empty array

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [16]:
np.zeros((3,4),dtype=bool) # you  will get an array is it contains zeros-false ,ones-True

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])