<a href="https://colab.research.google.com/github/Kunalkumar9354/Leetcode-Practice/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [8]:
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
y=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(y)
z=np.array([1,2,3])
print(z)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[1 2 3]


In [9]:
x.shape

(2, 4)

In [10]:
y.shape

(3, 5)

In [18]:
df=pd.DataFrame(y)

In [20]:
df.head()

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

In [22]:
x=np.arange(1,10,dtype=float)
print(x)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [27]:
x=np.arange(1,10).reshape(3,3)# to create a 3 dimesional array
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
x.shape

(3, 3)

In [33]:
#dtype is not a function
print(x.dtype)

int64


In [37]:
print(x.size)
x.transpose()

9


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
np.empty((4,4),dtype=int)
np.empty((3,3),dtype=float)
np.empty((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
np.ones((3,3),dtype=int)
np.ones((3,3),dtype=bool)
np.zeros((3,3),dtype=bool)


array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [54]:
a=np.arange(1,5).reshape(2,2)
b=np.arange(5,9).reshape(2,2)
np.add(a,b)
np.multiply(a,b)
np.divide(a,b)
np.dot(a,b)
np.subtract(a,b)


array([[-4, -4],
       [-4, -4]])

In [59]:
z=np.arange(1,11,dtype=int).reshape(2,5)
z=z.reshape(1,10)
print(z)

[[ 1  2  3  4  5  6  7  8  9 10]]


In [61]:
z=np.arange(1,11,dtype=int).reshape(2,5)
z=z.flatten()
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


In [64]:
z=z.ravel() #  it also flatten the array but i doesnt occupy memory
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


In [69]:
z=np.arange(1,11,dtype=int).reshape(2,5)
print(z)
z[0]
z[1]
z[1,2] #first row and second column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


8

In [86]:
ele=z[1:,3]
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [90]:
np.random.random((3,3))


array([[0.0874866 , 0.33111048, 0.57676295],
       [0.56399509, 0.90797512, 0.580862  ],
       [0.76327746, 0.90447322, 0.60260213]])

In [91]:
np.random.random((1,2))

array([[0.90743836, 0.76426423]])

In [92]:
np.random.randint(1,10)


1

In [96]:
np.random.randint(1,10,(2,2))

array([[9, 7],
       [7, 1]])

In [99]:
np.random.randint(1,10,(3,3,3))#3 layer ,3 row , 3column

array([[[1, 4, 1],
        [6, 8, 5],
        [5, 9, 4]],

       [[2, 7, 5],
        [2, 7, 8],
        [4, 8, 5]],

       [[4, 2, 1],
        [3, 8, 5],
        [4, 2, 4]]])

In [101]:
np.random.randint(1,10,(3,2,2)) #this first 3 is for layer

array([[[5, 8],
        [6, 9]],

       [[4, 5],
        [5, 1]],

       [[2, 1],
        [6, 1]]])

In [107]:
np.random.randint(1,10)
c=np.arange(1,10)
np.random.choice(c)

5

In [111]:
np.random.randint(1,10)

1

In [121]:
s1="Kunal"
s2="amit"
s3="my name is\namit"
np.char.add(s1,s2)
np.char.split(s1)
np.char.split(s2)
np.char.upper(s1)
np.char.lower(s2)
np.char.islower(s1)
np.char.isupper(s2)
print(np.char.splitlines(s3))

['my name is', 'amit']


In [124]:
# count
s4="amit badana"
counter=0
for i in range(len(s4)):
  counter+=1
print(counter)

11
