<a href="https://colab.research.google.com/github/Kunalkumar9354/Leetcode-Practice/blob/main/random_func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
np.random.random()

0.8519230104436862

In [6]:
np.random.random(2)

array([0.22282684, 0.9776913 ])

In [9]:
np.random.random((4,4))

array([[0.54698079, 0.27393516, 0.4169128 , 0.7235344 ],
       [0.45446915, 0.13525176, 0.98116461, 0.21993933],
       [0.44992532, 0.75280158, 0.36578284, 0.15650103],
       [0.87667128, 0.93279451, 0.2953671 , 0.73329288]])

In [12]:
np.random.randint(1,10)

4

In [13]:
np.random.randint(1,10,(2,2))

array([[3, 9],
       [5, 4]])

In [16]:
np.random.randint(1,10,(3,4,5))

array([[[9, 4, 7, 1, 6],
        [1, 6, 2, 8, 8],
        [4, 5, 4, 6, 4],
        [5, 4, 2, 9, 8]],

       [[9, 7, 1, 2, 9],
        [4, 9, 4, 4, 9],
        [6, 6, 8, 1, 8],
        [7, 5, 7, 6, 2]],

       [[2, 9, 2, 7, 8],
        [4, 8, 9, 2, 8],
        [4, 9, 5, 9, 2],
        [5, 7, 6, 8, 1]]])

In [26]:
np.random.randn(3,4,5) #3 layer 4 rows 5 column
a=np.arange(1,10)
print(a)
np.random.choice(a)

[1 2 3 4 5 6 7 8 9]


7