<a href="https://colab.research.google.com/github/Kunalkumar9354/Leetcode-Practice/blob/main/slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np

In [12]:
np.arange(1,4,2) #start end step (loop)

array([1, 3])

you cant reshape if there are more elements in array as compare to the shape you want

In [14]:
a=np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]


In [15]:
a=a.reshape(3,3)
print(a)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [16]:
b =np.arange(1,5)
print(b)

[1 2 3 4]


In [17]:
b=b.reshape(2,2)
print(b)

[[1 2]
 [3 4]]


In [18]:
nums=np.arange(1,51)
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [19]:
nums=nums.reshape((10,5))
print(nums)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [20]:
nums = nums.flatten() #return the one dimension array
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [21]:
nums=nums.ravel()
print(nums)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [22]:
nums = nums.reshape((10,5))
print(nums)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]


In [31]:
nums[0]

array([1, 2, 3, 4, 5])

In [32]:
nums[1]

array([ 6,  7,  8,  9, 10])

In [23]:
nums[1,3]

9

In [26]:
nums[4,4]

25

In [32]:
nums[0:10]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [35]:
nums[0,3]

4

In [38]:
nums[:,2] #you can acess specific columns

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [39]:
nums[:,3]

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49])

In [40]:
nums[2:5,4]

array([15, 20, 25])

In [45]:
nums[:2:5]

array([[1, 2, 3, 4, 5]])